config/routes.rb
Rails.application.routes.draw do
  mount Shoppe::Engine => "/shoppe"
  
  get 'product/:permalink' => 'products#show', :as => 'product'
  post 'product/:permalink' => 'products#buy'

  get 'products' => 'products#index'

  root :to => 'site#index'

  get 'basket' => 'orders#show'

  delete 'basket' => 'orders#destroy'

  match 'checkout' => 'orders#checkout', :as => 'checkout', :via => [:get, :patch]
  post 'checkout/pay' => 'orders#payment', :as => 'checkout_payment'
  match 'checkout/confirm' => 'orders#confirmation', :as => 'checkout_confirmation', :via => [:get, :post]
  
  post "/hook" => "orders#hook"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private 

	  def current_order
	    @current_order ||= begin
	      if has_order?
	        @current_order
	      else
	        order = Shoppe::Order.create(:ip_address => request.ip)
	        session[:order_id] = order.id
	        order
	      end
	    end
	  end

	  def has_order?
	    !!(
	      session[:order_id] &&
	      @current_order = Shoppe::Order.includes(:order_items => :ordered_item).find_by_id(session[:order_id])
	    )
	  end

	  helper_method :current_order, :has_order?
	  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	def destroy
  		current_order.destroy
  		session[:order_id] = nil
  		redirect_to :back
  	end

  def checkout
    @order = Shoppe::Order.find(current_order.id)
    if request.patch?
      if @order.proceed_to_confirm(params[:order].permit(:first_name, :last_name, :billing_address1, :billing_address2, :billing_address3, :billing_address4, :billing_country_id, :billing_postcode, :email_address, :phone_number))
        current_order.confirm!
        values = {
              business: "merchant@cesteforte.com",
              cmd: "_xclick",
              upload: 1,
              return: "#{Rails.application.secrets.app_host}#{checkout_confirmation_path}",
              invoice: current_order.id,
              item_name: "Ceste Forte Order",
              amount: @order.total.round(2),
              notify_url: "#{Rails.application.secrets.app_host}/hook",
              quantity: '1'
          }
         url="#{Rails.application.secrets.paypal_host}/cgi-bin/webscr?" + values.to_query
         redirect_to url
      end
    end
  end

  def confirmation
  end

   protect_from_forgery except: [:hook]
   def hook
    params.permit! # Permit all Paypal input params
    status = params[:payment_status]
    if status == "Completed"
      @order = Shoppe::Order.find(params[:invoice]) 
      payment = @order.payments.build(amount: @order.total,method: "paypal",reference: @order.number)
      payment.save
    end
    render nothing: true
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Shoppe::Product.root.ordered.includes(:product_category, :variants)
		puts YAML::dump(@products)
    	@products = @products.group_by(&:product_category)
	end

	def show
		@product = Shoppe::Product.find_by_permalink(params[:permalink])
	end

	def buy
  		@product = Shoppe::Product.find_by_permalink!(params[:permalink])
  		current_order.order_items.add_item(@product, 1)
  		redirect_to :back
	end

	def remove
		@item = Shoppe::Product.find_by_name(params[:item_name])
		@item.remove
	end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cestforte</title>
  <%= stylesheet_link_tag   'site' ,'data-turbolinks-track' => true%>
  <%= stylesheet_link_tag 'products','data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'bootstrap.min','data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<link href='http://fonts.googleapis.com/css?family=Quicksand' rel='stylesheet' type='text/css'>
</head>
<body>

  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
         <img alt="Ceste Forte" src="<%= asset_path 'logoAccent.png' %>">
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a href="/products">Store</a></li>
          <li><a href="">Look_Book</a></li>
          <li><a href="">About</a></li>
          <li><a href="">Contact</a></li>
        </ul>
        <div class="navbar-right">
        <% if has_order? %>
          <b><%= current_order.total_items%>X</b>
          <%= link_to number_to_currency(current_order.total_before_tax), basket_path %>
          <img src="<%= asset_path 'carticon.png'%>" >
        <% end %>
      </div>
      </div>
    </div>
  </nav>



<%= yield %>

</body>
</html>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cestforte</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'splash' , 'data-turbolinks-track' =>true%>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
</head>
<body>
<%= yield %>

</body>
</html>

app/views/orders/_items.html.erb
<table class="table table-hover" width='100%' border='1'>
  <thead>
    <tr>
      <td>Quantity</td>
      <td>Product</td>
      <td>Sub-Total</td>
      <td>Tax</td>
      <td>Total</td>

    </tr>
  </thead>
  <tbody>
    <% order.order_items.each do |item| %>
    <tr>
      <td><%= item.quantity %></td>
      <td><%= item.ordered_item.full_name %></td>
      <td><%= number_to_currency item.sub_total %></td>
      <td><%= number_to_currency item.tax_amount %></td>
      <td><%= number_to_currency item.total %></td>
    </tr>
    <% end %>

    <% if order.delivery_service %>
    <tr>
      <td></td>
      <td><%= order.delivery_service.name %></td>
      <td><%= number_to_currency order.delivery_price %></td>
      <td><%= number_to_currency order.delivery_tax_amount %></td>
      <td><%= number_to_currency order.delivery_price + order.delivery_tax_amount %></td>
    </tr>
    <% end %>
</table>
  <div class="total">
    <p><b>Sub-Total:</b><%= number_to_currency order.total_before_tax %></p>
    <p><b>Tax:</b><%= number_to_currency order.tax %></p>
    <p><b>Total:</b><%= number_to_currency order.total %></p>
  </div>

app/views/orders/checkout.html.erb
<div class="container">
<h2>Checkout</h2>
<div class="well">
<%= render 'items', :order => @order %>
</div>
    <div class="well text-center">
  

            <%= simple_form_for @order, :url => checkout_path, defaults: { input_html: { class: 'form-control input-lg' } } ,html: {class: 'form-inline' } do |f| %>
      <div class="row">
        <%= f.input :first_name, class: 'form-control input-lg', placeholder: "First Name", label: 'First Name'%> 
        <%= f.input :last_name, placeholder:"Last Name", label:'Last Name'%>
    </div>
        <%= f.input :billing_address1, placeholder: "Street", label: 'Street Address'%>
        <%= f.input :billing_address2, placeholder: "Apt #" %>
        <%= f.input :billing_address3, placeholder: "City", label:'City'%>    
        <%= f.input :billing_address4, placeholder: "State", label: 'State' %>
        <%= f.input :billing_postcode, placeholder: "00000", label: 'Zipcode' %>

        <%= f.input :billing_country_id, :as => :hidden ,:input_html => { :value => "United States" } %>
        <%= f.input :email_address, label: 'Email Address', placeholder: "gucci@moneymaker.com" %>
        <%= f.input :phone_number, label: 'Phone Number', placeholder:"7777777777" %>

        <%= f.submit 'Continue', class: 'btn btn-success' %>
      
    <% end %>
    </div>
</div>

app/views/orders/confirmation.html.erb
<h2>Thank You for Placing your Order </h2>
<%= render 'items', :order => current_order %>

app/views/orders/show.html.erb
<div class="container">
	<div class="panel panel-warning">
		<div class="panel-heading"><h2>Your basket</h2></div>
		<div class="panel-body">
			<%= render 'items', :order => current_order %>
		</div>
		<div class="panel-footer">
			<%= link_to 'Empty basket', basket_path, class: "btn btn-danger" ,:method => :delete %>
      <%= link_to "Checkout", checkout_path , class: "btn btn-success pull-right"%>
		</div>
	</div>	
</div>